-- Deprecated entrypoint.
--
-- Use supabase/schema_production.sql for new Supabase projects.
-- Existing projects should apply the files in supabase/migrations/ in order.
--
-- This placeholder intentionally avoids defining an outdated partial schema.
