/* eslint-disable @typescript-eslint/no-require-imports */
const assert=require('node:assert/strict'),path=require('node:path'),sharp=require('sharp');
module.exports=async function({page,context,browser,db,origin,report,out,observe,setMode,files}) {
  const post=data=>context.request.post(origin+'/admin/creator/api',{headers:{Origin:origin},data});
  assert.equal((await context.request.get(origin+'/admin/creator/api')).status(),200);
  const tier=(await db.query('select * from public.creator_tier_works')).rows[0];
  const assets=(await db.query('select * from public.creator_images order by created_at')).rows;
  const document={...tier.document,title:'環境解説セット・手動相性',showTitle:true,rows:tier.document.rows.map((r,i)=>({...r,imageIds:i===0?assets.slice(0,2).map(a=>a.id):i===1?[assets[2].id]:[]}))};
  assert.equal((await post({action:'save',id:tier.id,revision:tier.revision,document})).status(),200);
  await page.goto(origin+'/admin/creator/tier?work='+tier.id,{waitUntil:'networkidle'});
  await page.getByRole('button',{name:'相関図を追加',exact:true}).first().click();
  await page.getByRole('heading',{name:'相関図を編集',exact:true}).waitFor();
  const route='/admin/creator/tier/'+tier.id+'/correlation';
  const read=async()=>(await db.query('select * from public.creator_correlations')).rows[0];
  let graph=await read();
  assert.equal(graph.tier_work_id,tier.id); assert.deepEqual(graph.document.nodes.map(n=>n.imageId),assets.slice(0,3).map(a=>a.id));
  assert.ok(graph.document.nodes[0].y<graph.document.nodes[2].y);
  assert.equal(graph.document.title,document.title);
  await page.getByLabel('相関図タイトル',{exact:true}).fill('独立した相関図');
  const first=graph.document.nodes[0].id,second=graph.document.nodes[1].id;
  await page.getByLabel('選択ノード',{exact:true}).selectOption(first);
  await page.getByLabel('X座標',{exact:true}).fill('200'); await page.getByLabel('Y座標',{exact:true}).fill('200');
  for(const width of [1920,1440,768,390,320]) {
    await page.setViewportSize({width,height:1080});
    const control=page.locator(`[data-node-id="${first}"]`); await control.scrollIntoViewIfNeeded();
    const box=await control.boundingBox(),scale=(await page.locator('[data-correlation-canvas]').boundingBox()).width/1920;
    const before=Number(await page.getByLabel('X座標',{exact:true}).inputValue());
    await page.mouse.move(box.x+box.width/2,box.y+box.height/2); await page.mouse.down(); await page.mouse.move(box.x+box.width/2+80*scale,box.y+box.height/2,{steps:5}); await page.mouse.up();
    assert.ok(Math.abs(Number(await page.getByLabel('X座標',{exact:true}).inputValue())-before-80)<=2,`${width}: logical drag`);
    await page.screenshot({path:path.join(out,`correlation-editor-${width}.png`),fullPage:true});
    const overflow=await page.locator('main').evaluate(el=>[...el.querySelectorAll('button,input,select,a')].filter(n=>{const b=n.getBoundingClientRect();return b.width&&(b.right>innerWidth+1||b.left< -1);}).map(n=>n.outerHTML.slice(0,100)));
    assert.deepEqual(overflow,[],`${width}: controls fit`);
  }
  await page.setViewportSize({width:1920,height:1080});
  await page.getByLabel('X座標',{exact:true}).fill('9999');
  assert.ok(Number(await page.getByLabel('X座標',{exact:true}).inputValue())<=1896);
  await page.getByRole('button',{name:'画像サイズL',exact:true}).click();
  assert.equal(Number(await page.getByLabel('X座標',{exact:true}).inputValue()),1680);
  await page.getByRole('button',{name:'画像サイズM',exact:true}).click();
  await page.getByLabel('X座標',{exact:true}).fill('200'); await page.getByLabel('Y座標',{exact:true}).fill('200');
  await page.locator(`[data-node-id="${first}"]`).focus(); await page.keyboard.press('Shift+ArrowRight');
  assert.equal(await page.getByLabel('X座標',{exact:true}).inputValue(),'210');
  await page.getByLabel('接続元',{exact:true}).selectOption(first); await page.getByLabel('接続先',{exact:true}).selectOption(first);
  assert.equal(await page.getByRole('button',{name:'矢印を追加',exact:true}).isDisabled(),true);
  await page.getByLabel('接続先',{exact:true}).selectOption(second); await page.getByRole('button',{name:'矢印を追加',exact:true}).click();
  await page.getByLabel('矢印1のラベル',{exact:true}).fill('かなり有利・自由入力');
  await page.getByLabel('矢印1の種類',{exact:true}).selectOption('bidirectional');
  assert.equal(await page.locator('[data-edge-id] polygon').count(),2);
  const anchors=await page.locator('[data-edge-id] polygon').evaluateAll(es=>es.map(e=>e.getAttribute('points')));
  await page.getByRole('button',{name:'画像サイズL',exact:true}).click();
  assert.notDeepEqual(await page.locator('[data-edge-id] polygon').evaluateAll(es=>es.map(e=>e.getAttribute('points'))),anchors);
  await page.getByRole('button',{name:'画像サイズM',exact:true}).click();
  await page.getByLabel('X座標',{exact:true}).fill('220');
  assert.notDeepEqual(await page.locator('[data-edge-id] polygon').evaluateAll(es=>es.map(e=>e.getAttribute('points'))),anchors);
  await page.getByLabel('X座標',{exact:true}).fill('210');
  await page.getByLabel('矢印1の種類',{exact:true}).selectOption('forward');
  assert.equal(await page.locator('[data-edge-id] polygon').count(),1);
  await page.getByLabel('矢印1の種類',{exact:true}).selectOption('bidirectional');
  await page.getByLabel('矢印1の勝率',{exact:true}).fill('0');
  await page.getByLabel('矢印1の対戦数',{exact:true}).fill('0');
  assert.ok((await page.locator('[data-edge-id]').textContent()).includes('0% / 0戦'));
  await page.getByLabel('矢印1の勝率',{exact:true}).fill('57.1');
  await page.getByLabel('矢印1の対戦数',{exact:true}).fill('');
  assert.ok((await page.locator('[data-edge-id]').textContent()).includes('57.1%'));
  assert.ok(!(await page.locator('[data-edge-id]').textContent()).includes('戦'));
  await page.getByLabel('矢印1の勝率',{exact:true}).fill('');
  assert.equal(await page.locator('[data-edge-id] text').count(),1);
  await page.getByLabel('矢印1の対戦数',{exact:true}).fill('42');
  assert.ok((await page.locator('[data-edge-id]').textContent()).includes('42戦'));
  await page.getByLabel('矢印1の勝率',{exact:true}).fill('57.1');
  await page.getByLabel('矢印ラベルを表示',{exact:true}).uncheck();
  assert.ok(!(await page.locator('[data-edge-id]').textContent()).includes('自由入力'));
  await page.getByLabel('矢印ラベルを表示',{exact:true}).check();
  await page.getByLabel('勝率・対戦数を表示',{exact:true}).uncheck();
  assert.ok(!(await page.locator('[data-edge-id]').textContent()).includes('57.1'));
  await page.getByLabel('勝率・対戦数を表示',{exact:true}).check();
  await page.getByRole('button',{name:'方向を反転',exact:true}).click();
  await page.getByLabel('矢印1を表示',{exact:true}).uncheck(); assert.equal(await page.locator('[data-edge-id]').count(),0);
  await page.getByLabel('矢印1を表示',{exact:true}).check(); assert.equal(await page.locator('[data-edge-id]').count(),1);
  await page.getByRole('button',{name:'矢印を追加',exact:true}).click(); await page.getByRole('alert').filter({hasText:'1本だけ'}).waitFor();
  // A cancelled navigation leaves all unsaved work in place.
  page.removeAllListeners('dialog'); page.on('dialog',d=>d.dismiss());
  await page.getByRole('link',{name:'Tier表に戻る',exact:true}).click(); assert.ok(page.url().endsWith(route));
  page.removeAllListeners('dialog'); page.on('dialog',d=>d.accept());
  await page.getByRole('button',{name:'相関図を保存',exact:true}).click(); await page.getByRole('status').filter({hasText:'相関図を保存しました'}).waitFor();
  graph=await read(); assert.equal(graph.document.edges[0].origin,'manual'); assert.equal(graph.document.edges[0].sourceNodeId,second);
  for(const values of [{winRate:101},{winRate:-1},{matchCount:1.5},{matchCount:-1},{winRate:'57'}])assert.equal((await post({action:'save-correlation',id:graph.id,revision:graph.revision,document:{...graph.document,edges:[{...graph.document.edges[0],...values}]}})).status(),400);
  await page.reload({waitUntil:'networkidle'}); assert.equal(await page.getByLabel('X座標',{exact:true}).inputValue(),'210');
  assert.equal((await post({action:'save-correlation',id:graph.id,revision:graph.revision-1,document:graph.document})).status(),409);
  const currentTier=(await db.query('select * from public.creator_tier_works')).rows[0];
  const changedTier=await post({action:'save',id:tier.id,revision:currentTier.revision,document:{...currentTier.document,title:'変更後のTier'}});assert.equal(changedTier.status(),200);currentTier.revision++;
  await page.reload({waitUntil:'networkidle'});
  assert.equal(await page.getByLabel('相関図タイトル',{exact:true}).inputValue(),'独立した相関図');
  assert.equal(await page.getByLabel('矢印1の勝率',{exact:true}).inputValue(),'57.1');
  assert.equal(await page.getByLabel('矢印1の対戦数',{exact:true}).inputValue(),'42');
  assert.equal(await page.locator('[data-edge-id] polygon').count(),2);
  assert.equal((await post({action:'delete-work',id:tier.id,revision:currentTier.revision})).status(),409);
  const used=(await db.query('select * from public.creator_images where id=$1',[assets[0].id])).rows[0];
  assert.equal((await post({action:'delete-image',id:used.id,revision:used.revision})).status(),409);
  // Replacement keeps the image ID in both documents and refreshes both renderers.
  const replacement=await context.request.post(origin+'/admin/creator/api',{headers:{Origin:origin},multipart:{file:files[1],id:used.id,revision:String(used.revision)}}); assert.equal(replacement.status(),200);
  await page.reload({waitUntil:'networkidle'});
  const obs=await context.newPage(); observe(obs); await obs.setViewportSize({width:1920,height:1080});
  await obs.goto(origin+'/admin/obs/set/'+tier.id,{waitUntil:'networkidle'});
  assert.ok((await obs.locator('[data-correlation-artwork]').textContent()).includes('独立した相関図'));
  assert.ok((await obs.locator('[data-correlation-artwork]').textContent()).includes('57.1% / 42戦'));
  assert.equal(await obs.locator('[data-edge-id] polygon').count(),2);
  assert.equal(await obs.locator('button,nav,input,select').count(),0);
  const boxes=await obs.locator('[data-obs-section]').evaluateAll(es=>es.map(e=>{const b=e.getBoundingClientRect();return [b.x,b.y,b.width,b.height];}));
  assert.deepEqual(boxes,[[0,0,1920,1080],[0,1080,1920,1080]]);
  const imageUrls=await obs.locator(`img[src*="${used.id}"]`).evaluateAll(es=>es.map(e=>e.getAttribute('src'))); assert.equal(new Set(imageUrls).size,1); assert.equal(imageUrls.length,2);
  await obs.evaluate(()=>scrollTo(0,1080)); assert.equal(await obs.evaluate(()=>scrollY),1080);
  await obs.screenshot({path:path.join(out,'correlation-obs.png')});
  const download=page.waitForEvent('download'); await page.getByRole('button',{name:'相関図PNG',exact:true}).click();
  const pngPath=path.join(out,'correlation.png'); await (await download).saveAs(pngPath);
  const meta=await sharp(pngPath).metadata(); assert.equal(meta.width,1920);assert.equal(meta.height,1080);
  const a=await sharp(pngPath).removeAlpha().raw().toBuffer(),b=await sharp(path.join(out,'correlation-obs.png')).removeAlpha().raw().toBuffer();
  let difference=0;for(let i=0;i<a.length;i++)difference+=Math.abs(a[i]-b[i]);
  report.correlationPixelMeanDifference=difference/a.length; assert.ok(difference/a.length<3,'PNG includes SVG arrows/labels and matches OBS');
  await obs.goto(origin+'/admin/obs/correlation/'+tier.id,{waitUntil:'networkidle'}); assert.equal(await obs.locator('[data-obs-section]').count(),1);
  await page.getByLabel('相関図タイトルを表示',{exact:true}).uncheck(); await page.getByLabel('デッキ名を表示',{exact:true}).uncheck();
  await page.getByLabel('PNG・OBSの背景を透明にする',{exact:true}).check();
  const alphaDownload=page.waitForEvent('download'); await page.getByRole('button',{name:'相関図PNG',exact:true}).click();
  const alphaPath=path.join(out,'correlation-transparent.png'); await (await alphaDownload).saveAs(alphaPath);
  assert.equal((await sharp(alphaPath).ensureAlpha().raw().toBuffer())[3],0);
  await page.getByRole('button',{name:'相関図を保存',exact:true}).click(); await page.getByRole('status').filter({hasText:'相関図を保存しました'}).waitFor();
  await obs.goto(origin+'/admin/obs/set/'+tier.id+'?transparent=1',{waitUntil:'networkidle'});
  assert.equal(await obs.locator('body').evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(0, 0, 0, 0)');
  const routes=[route,'/admin/obs/set/'+tier.id,'/admin/obs/correlation/'+tier.id];
  for(const role of ['member','guest']) {setMode(role);for(const r of routes)assert.equal((await context.request.get(origin+r,{maxRedirects:0})).status(),307);assert.equal((await post({action:'save-correlation',id:graph.id,revision:graph.revision,document:graph.document})).status(),role==='member'?403:401);}
  setMode('admin'); const anon=await browser.newContext();for(const r of routes)assert.equal((await anon.request.get(origin+r,{maxRedirects:0})).status(),307);await anon.close();
  report.checks.push('Phase 2: inherited Tier images, 5 viewport logical drag/overflow, bounds/resize/keyboard, manual edges/reverse/label/hide/duplicate/self, unsaved guard, save/reload/conflict, parent/image delete restriction, shared image replacement, stacked 2160px OBS and scroll, PNG1920 with SVG matches OBS, transparent/title/name toggles, direct permissions');
  if(process.env.CORRELATION_BROWSER_HOLD==='1'){console.log('READY_FOR_CORRELATION_BROWSER');await new Promise(r=>setTimeout(r,45000));}
  await page.getByRole('button',{name:'画像ノードを追加',exact:true}).click(); const added=await page.getByLabel('選択ノード',{exact:true}).inputValue();
  await page.getByLabel('接続先',{exact:true}).selectOption(added);await page.getByRole('button',{name:'矢印を追加',exact:true}).click();assert.equal(await page.locator('[data-edge-editor]').count(),2);
  await page.getByRole('button',{name:'ノードを削除',exact:true}).click();assert.equal(await page.locator('[data-edge-editor]').count(),1);
  await page.getByRole('button',{name:'矢印を削除',exact:true}).click();assert.equal(await page.locator('[data-edge-editor]').count(),0);
  await page.getByRole('button',{name:'相関図を削除',exact:true}).click();await page.waitForURL('**/admin/creator/tier?work=*');
  assert.equal((await db.query('select * from public.creator_correlations')).rows.length,0);assert.equal((await db.query('select * from public.creator_tier_works')).rows.length,1);
  await obs.close();report.checks.push('Phase 2: node removal prunes incident edges, explicit arrow removal, diagram removal preserves parent Tier and library');
};
