/* eslint-disable @typescript-eslint/no-require-imports */
const {test}=require('node:test'),assert=require('node:assert/strict');
const {parseCorrelation,correlationFromTier}=require('../src/lib/creator/correlation');
const {newTierDocument,tierLayout,tierImagePosition}=require('../src/lib/creator/model');
const {parseDataSelection,withAutomaticData,matchupCandidates}=require('../src/lib/creator/matchup-data');
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const selection={environment:id(99),period:'7d',ranks:['unranked']};
function fixture(){const doc=correlationFromTier({...newTierDocument(),rows:[{id:id(1),name:'S',color:'#ffffff',imageIds:[id(10),id(11),id(12)]}]});const data={selection,start:'2026-10-01T00:00:00Z',end:'2026-10-02T00:00:00Z',aggregatedAt:'2026-10-02T00:01:00Z',imageDecks:{[id(10)]:id(20),[id(11)]:id(21),[id(12)]:id(22)},cells:[{sourceDeckId:id(20),targetDeckId:id(21),winRate:57.142857,matchCount:42},{sourceDeckId:id(21),targetDeckId:id(20),winRate:42.857143,matchCount:42},{sourceDeckId:id(22),targetDeckId:id(20),winRate:61.3,matchCount:31},{sourceDeckId:id(22),targetDeckId:id(21),winRate:90,matchCount:29}]};const edge={id:id(40),sourceNodeId:doc.nodes[0].id,targetNodeId:doc.nodes[1].id,origin:'manual',label:'有利',visible:true};return{doc,data,edge};}
test('creator board: shared row-derived image frames fill82%, wrap and stay inside logical artwork',()=>{for(const count of [0,1,5,12,30,100]){const d=newTierDocument();d.rows.forEach(r=>r.imageIds=Array(count).fill(id(2)));const l=tierLayout(d);assert.ok(l.imageSize>128);assert.ok(l.contentHeight*l.scale<=912.00001);for(let i=0;i<count;i++){const p=tierImagePosition(l,i);assert.ok(p.left>=0&&p.top>=0&&p.left+p.width<=1664&&p.top+p.height<=l.heights[0]);}if(count<=l.columns)assert.ok(l.imageSize/l.heights[0]>=.75&&l.imageSize/l.heights[0]<=.85);}});
test('creator auto values: perspective lookup, missing deck/no data and legacy manual compatibility',()=>{const {doc,data,edge}=fixture();const a=withAutomaticData(doc,edge,data);assert.equal(a.winRate,57.1);assert.equal(a.matchCount,42);assert.equal(withAutomaticData(doc,{...edge,sourceNodeId:edge.targetNodeId,targetNodeId:edge.sourceNodeId},data).winRate,42.9);const z=withAutomaticData(doc,edge,{...data,cells:[{...data.cells[0],winRate:null,matchCount:0}]});assert.equal(z.winRate,null);assert.equal(z.matchCount,0);assert.equal(withAutomaticData(doc,edge,{...data,imageDecks:{}}).dataSnapshot,undefined);const parsed=parseCorrelation({...doc,dataSelection:selection,edges:[a]});assert.deepEqual(parseCorrelation(JSON.parse(JSON.stringify(parsed))),parsed);const legacy=parseCorrelation({...doc,edges:[{...edge,winRate:63.2,matchCount:7}]});assert.equal(legacy.edges[0].dataSource,undefined);assert.equal(legacy.edges[0].winRate,63.2);assert.equal(legacy.edges[0].matchCount,7);for(const p of [{dataSource:'invalid'},{dataSnapshot:{}},{dataSnapshot:{...a.dataSnapshot,start:a.dataSnapshot.end}}])assert.throws(()=>parseCorrelation({...doc,edges:[{...a,...p}]}));assert.throws(()=>parseDataSelection({...selection,ranks:[]}));});
test('creator candidates: exact sample/percentage cutoffs, one direction and preserve existing manual pairs',()=>{const {doc,data,edge}=fixture();assert.equal(matchupCandidates(doc,data,30,55).length,2);assert.equal(matchupCandidates(doc,data,42,55).length,1);assert.equal(matchupCandidates(doc,data,30,60).length,1);assert.equal(matchupCandidates({...doc,edges:[edge]},data,30,55).length,1);assert.equal(matchupCandidates(doc,{...data,cells:[{...data.cells[0],winRate:54.99}]},30,55).length,0);assert.equal(matchupCandidates(doc,{...data,cells:[{...data.cells[0],matchCount:0}]},0,55).length,0);assert.equal(matchupCandidates(doc,{...data,cells:data.cells.slice(0,2).map(c=>({...c,winRate:50}))},30,50).length,1);assert.throws(()=>matchupCandidates(doc,data,-1,55));assert.throws(()=>matchupCandidates(doc,data,30,49));});
test('creator loader reuses OBS RPC arguments, strict parser and exact matrix values for each filter',async()=>{
 const {dashboard,environments,decks}=require('./obs-environment-fixture.cjs'),{aggregates}=require('./obs-matchups-fixture.cjs');let args,raw=aggregates(),error=null;
 const serverId=require.resolve('../src/lib/supabase/server');const client={rpc:async(name,p)=>{if(name==='get_environment_dashboard_aggregates_v3')return{data:dashboard(p),error:null};args={name,p};return{data:raw,error};},from:table=>{assert.equal(table,'creator_images');return{select:()=>({in:async(_k,ids)=>({data:ids.map((key,i)=>({id:key,archetype_id:decks[i].id})),error:null})})};}};
 require.cache[serverId]={id:serverId,filename:serverId,loaded:true,exports:{createSupabaseServerClient:async()=>client}};
 const {getCreatorMatchups}=require('../src/lib/creator/matchup-server'),{getObsEnvironmentMatchups}=require('../src/lib/obs-environment-matchups');
 for(const period of ['24h','3d','7d','30d'])for(const ranks of [['unranked'],['master:ruby']]){
  const s={environment:environments[0].id,period,ranks},d=dashboard({p_environment_id:s.environment,p_period:period,p_rank_filters:ranks});const result=await getCreatorMatchups(client,s,[id(10),id(11)]),creatorArgs=structuredClone(args);const obs=await getObsEnvironmentMatchups(d);assert.deepEqual(args,creatorArgs);
  for(const c of result.cells){const existing=obs.find(r=>r.myDeck.id===c.sourceDeckId).cells.find(v=>v.opponentDeckId===c.targetDeckId);assert.equal(c.winRate,existing.winRate);assert.equal(c.matchCount,existing.total);}assert.equal(result.start,d.current.start);assert.equal(result.end,d.current.end);
 }
 error={code:'XX000'};await assert.rejects(()=>getCreatorMatchups(client,{...selection,environment:environments[0].id},[id(10)]));error=null;raw={};await assert.rejects(()=>getCreatorMatchups(client,{...selection,environment:environments[0].id},[id(10)]));
});
