/* eslint-disable @typescript-eslint/no-require-imports */
// Built UI -> recording localhost proxy -> actual Supabase. Never calls Production.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'build/e12'),origin='http://localhost:3274';
function read(file){const raw=fs.readFileSync(file);return JSON.parse(raw.toString(raw[0]===255?'utf16le':'utf8').replace(/^\uFEFF/,''));}
const keys=read(out+'/keys.json'),sessions=read(out+'/sessions.json').sessions;assert.equal(keys.API_URL,'http://127.0.0.1:57321');
const f=require('./environment-dashboard-fixture.cjs'),atoms=['unranked',...f.leaves],presets=[['すべて',atoms],['Master以上',atoms.slice(7)],['Master',atoms.slice(7,12)],['GrandMaster',atoms.slice(12)]];
const custom=['master:sapphire','master:diamond','grandmaster:none','grandmaster:epic'];
const report={checks:[],errors:[],calls:[],focus:[],mobile:[]};let delay=0,app,browser,proxy,debugPage,failedMode=false;
const wait=ms=>new Promise(r=>setTimeout(r,ms)),count=name=>report.calls.filter(c=>c.name===name).length;
async function settled(page){await page.waitForLoadState('networkidle');await page.getByRole('status').filter({hasText:/読み込み中|ランク条件を適用中/}).waitFor({state:'hidden'});assert.equal(await page.locator('main [role=alert]').count(),0);}
const trigger=page=>page.locator('button[aria-haspopup=dialog]');
async function open(page){await trigger(page).click();await page.getByRole('dialog').waitFor();}
const box=(page,value)=>page.getByRole('dialog').locator('input[type=checkbox][value="'+value+'"]');
async function draft(page,selection){await page.getByRole('dialog').getByRole('button',{name:'Master',exact:true}).click();await page.getByRole('checkbox',{name:'Masterすべて',exact:true}).uncheck();for(const atom of selection)await box(page,atom).check();}
async function apply(page,name,selection){const start=count(name);await page.getByRole('dialog').getByRole('button',{name:'適用',exact:true}).click();await page.waitForURL(url=>url.searchParams.get('ranks')===selection.join(','));await settled(page);assert.equal(count(name)-start,1,'one aggregate RPC per apply');assert.equal(new URL(page.url()).searchParams.get('ranks'),selection.join(','));assert.equal(new URL(page.url()).searchParams.has('rank'),false);assert.deepEqual(report.calls.filter(c=>c.name===name).at(-1).args.p_rank_filters,selection);}
async function context(session,options={}){const c=await browser.newContext({viewport:{width:1365,height:1000},...options});await c.addCookies([{name:'sb-127-auth-token',value:'base64-'+Buffer.from(JSON.stringify(session)).toString('base64url'),url:origin}]);return c;}
(async()=>{try{proxy=http.createServer(async(req,res)=>{try{const started=Date.now();const chunks=[];for await(const chunk of req)chunks.push(chunk);const body=Buffer.concat(chunks),url=new URL(req.url,keys.API_URL),isRpc=url.pathname.includes('/rpc/');if(isRpc){report.calls.push({name:url.pathname.split('/').at(-1),args:JSON.parse(body.toString())});if(delay)await wait(delay);if(failedMode&&/get_(environment_dashboard|analysis)_aggregates_v[23]/.test(url.pathname)){res.writeHead(503,{'Content-Type':'application/json'});return res.end(JSON.stringify({code:'XX000',message:'Local injected failure'}));}}if(url.pathname==='/rest/v1/matches'){report.matchReads??=[];report.matchReads.push({columns:url.searchParams.get('select'),limit:url.searchParams.get('limit'),bounded:url.searchParams.get('id')?.startsWith('in.('),ownUser:url.searchParams.get('user_id')?.startsWith('eq.')});}
const r=await fetch(url,{method:req.method,headers:Object.fromEntries(Object.entries(req.headers).filter(([k])=>!['host','connection','content-length','accept-encoding'].includes(k))),...(body.length?{body}:{}),redirect:'manual'});res.writeHead(r.status,Object.fromEntries([...r.headers].filter(([k])=>!['connection','content-length','content-encoding','transfer-encoding'].includes(k))));const result=Buffer.from(await r.arrayBuffer());report.http??=[];report.http.push({path:url.pathname,status:r.status,ms:Date.now()-started,at:Date.now()});res.end(result);}catch(e){res.writeHead(502);res.end('{}');report.errors.push(e.message);}});await new Promise(r=>proxy.listen(57329,'127.0.0.1',r));
const log=fs.openSync(out+'/browser-server.log','w');app=spawn(process.execPath,[require.resolve('next/dist/bin/next'),'start','-p','3274'],{cwd:root,windowsHide:true,stdio:['ignore',log,log],env:{...process.env,NEXT_PUBLIC_SUPABASE_URL:'http://127.0.0.1:57329',NEXT_PUBLIC_SUPABASE_ANON_KEY:keys.ANON_KEY}});
for(let i=0;i<60;i++){try{if((await fetch(origin+'/privacy')).ok)break;}catch{}await wait(500);}
browser=await chromium.launch({headless:true,args:['--remote-debugging-port=9337'],...(process.env.CHROME_EXECUTABLE?{executablePath:process.env.CHROME_EXECUTABLE}:{})});
const member=await context(sessions[0]),page=await member.newPage();debugPage=page;page.on('pageerror',e=>{if(!failedMode)report.errors.push(e.message);});page.on('console',m=>{if(m.type()==='error'&&!failedMode)report.errors.push(m.text());});
for(const [route,name]of [['environment','get_environment_dashboard_aggregates_v2'],['analysis','get_analysis_aggregates_v3']].filter(([route])=>!process.env.TEST_ROUTE||route===process.env.TEST_ROUTE)){
await page.goto(origin+'/'+route+'?environment='+f.env.rankThree,{waitUntil:'networkidle'});await settled(page);assert.equal(await trigger(page).getAttribute('aria-expanded'),'false');const appliedUrl=page.url(),start=count(name);await open(page);assert.equal(await page.getByRole('dialog').locator('input[type=checkbox][value]').count(),17);assert.equal(await page.getByRole('dialog').getByRole('button',{name:'GrandMaster以上',exact:true}).count(),0);
for(const [label,ranks]of presets){await page.getByRole('dialog').getByRole('button',{name:label,exact:true}).click();assert.deepEqual(await page.getByRole('dialog').locator('input[type=checkbox][value]:checked').evaluateAll(es=>es.map(e=>e.value)),ranks);}
await page.getByRole('dialog').getByRole('button',{name:'Master',exact:true}).click();await box(page,'master:sapphire').uncheck();assert.equal(await page.getByRole('checkbox',{name:'Masterすべて',exact:true}).evaluate(e=>e.indeterminate),true);await page.getByRole('checkbox',{name:'Masterすべて',exact:true}).check();assert.equal(await page.getByRole('checkbox',{name:'Masterすべて',exact:true}).evaluate(e=>e.indeterminate),false);await page.getByRole('checkbox',{name:'Masterすべて',exact:true}).uncheck();assert.equal(await page.getByRole('button',{name:'適用',exact:true}).getAttribute('aria-disabled'),'true');await page.getByRole('button',{name:'適用',exact:true}).click({force:true});assert.equal(await page.getByRole('dialog').count(),1);assert.match(await page.getByRole('dialog').innerText(),/最低1区分/);await page.getByRole('button',{name:'キャンセル',exact:true}).click();assert.equal(page.url(),appliedUrl);assert.equal(count(name),start);assert.equal(await trigger(page).evaluate(e=>document.activeElement===e),true);report.checks.push(route+' presets/parent/indeterminate/empty/cancel; draft RPC=0');
for(const [label,ranks]of presets.slice(1)){await open(page);await page.getByRole('dialog').getByRole('button',{name:label,exact:true}).click();await apply(page,name,ranks);assert.match(await trigger(page).innerText(),new RegExp(label));}
await open(page);await draft(page,custom);const beforeApply=count(name);await wait(150);assert.equal(count(name),beforeApply);await apply(page,name,custom);assert.match(await trigger(page).innerText(),/カスタム（4区分）/);report.checks.push(route+' presets/custom apply one RPC');
await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('input[name=ranks]').inputValue(),custom.join(','));const shared=await member.newPage();await shared.goto(page.url(),{waitUntil:'networkidle'});assert.equal(await shared.locator('input[name=ranks]').inputValue(),custom.join(','));await shared.close();await page.goto(origin+'/privacy',{waitUntil:'networkidle'});await page.goBack({waitUntil:'networkidle'});await settled(page);assert.equal(await page.locator('input[name=ranks]').inputValue(),custom.join(','));await page.goForward({waitUntil:'networkidle'});assert.equal(new URL(page.url()).pathname,'/privacy');await page.goBack({waitUntil:'networkidle'});await settled(page);report.checks.push(route+' URL/reload/shared/back/forward');
if(route==='environment'){
assert.equal(new URL(await page.getByRole('link',{name:'自分の分析を見る'}).getAttribute('href'),origin).searchParams.get('ranks'),custom.join(','));assert.equal(await page.getByRole('link',{name:'自分の相性表を見る'}).getAttribute('aria-disabled'),'true');assert.match(await page.locator('main').innerText(),/このランクの組み合わせ/);
for(const period of ['24h','3d','30d','7d']){const n=count(name);await page.locator('label').filter({has:page.locator('input[name=period][value="'+period+'"]')}).click();await settled(page);assert.equal(count(name)-n,1);assert.equal(new URL(page.url()).searchParams.get('ranks'),custom.join(','));}await page.locator('select[name=environment]').selectOption(f.env.union||f.uuid(230));await settled(page);assert.equal(new URL(page.url()).searchParams.get('ranks'),custom.join(','));
await open(page);await page.getByRole('dialog').getByRole('button',{name:'Master',exact:true}).click();await apply(page,name,presets[2][1]);assert.equal(new URL(await page.getByRole('link',{name:'自分の相性表を見る'}).getAttribute('href'),origin).searchParams.get('rank'),'master');
}else{
const form=page.locator('form[action="/analysis"]');await form.locator('select[name=environment]').selectOption(f.env.ranks);await form.locator('select[name=winRateMode]').selectOption('combined');await form.locator('select[name=result]').selectOption('lose');await form.locator('select[name=turnOrder]').selectOption('second');await form.locator('select[name=myDeck]').selectOption(f.catalog[0].key);await form.locator('select[name=opponentDeck]').selectOption(f.catalog[1].key);await form.getByLabel('開始日時の日付',{exact:true}).fill('2026-09-01');await form.getByLabel('開始日時の時刻（日本時間）',{exact:true}).fill('09:15');await form.getByLabel('終了日時の日付',{exact:true}).fill('2026-10-31');await form.getByLabel('終了日時の時刻（日本時間）',{exact:true}).fill('21:40');
await open(page);await draft(page,['a','aa',...presets[2][1]]);await apply(page,name,['a','aa',...presets[2][1]]);
const appliedArgs=report.calls.filter(c=>c.name===name).at(-1).args;assert.equal(appliedArgs.p_environment_id,f.env.ranks);assert.equal(appliedArgs.p_include_reversed,true);assert.equal(appliedArgs.p_result,'lose');assert.equal(appliedArgs.p_turn_order,'second');assert.equal(appliedArgs.p_my_deck_id,f.catalog[0].key);assert.equal(appliedArgs.p_opponent_deck_id,f.catalog[1].key);assert.equal(appliedArgs.p_played_from,'2026-09-01T00:15:00.000Z');assert.equal(appliedArgs.p_played_to,'2026-10-31T12:40:59.999Z');
await open(page);await draft(page,custom);await apply(page,name,custom);const n=count(name);await form.getByRole('button',{name:'表示',exact:true}).click();await settled(page);assert.equal(count(name)-n,1);assert.equal(new URL(page.url()).searchParams.get('ranks'),custom.join(','));const args=report.calls.filter(c=>c.name===name).at(-1).args;assert.equal(args.p_include_reversed,true);assert.equal(args.p_result,'lose');assert.equal(args.p_turn_order,'second');assert.equal(args.p_my_deck_id,f.catalog[0].key);assert.equal(args.p_opponent_deck_id,f.catalog[1].key);
}
for(const legacy of ['all','master-plus','master:diamond','grandmaster-plus','grandmaster:none']){await page.goto(origin+'/'+route+'?environment='+f.env.rankThree+'&rank='+encodeURIComponent(legacy),{waitUntil:'networkidle'});await settled(page);assert.ok(await trigger(page).count());const expected=legacy==='all'?atoms:legacy==='master-plus'?atoms.slice(7):legacy==='grandmaster-plus'?atoms.slice(12):[legacy];assert.deepEqual(report.calls.filter(c=>c.name===name).at(-1).args.p_rank_filters,expected);}report.checks.push(route+' legacy URLs and unrelated filters preserved');
for(const width of [1365,390]){await page.setViewportSize({width,height:900});await page.goto(origin+'/'+route+'?environment='+f.env.rankThree,{waitUntil:'networkidle'});await trigger(page).focus();await page.keyboard.press('Enter');await page.getByRole('dialog').waitFor();await box(page,'unranked').focus();await page.keyboard.press('End');assert.equal(await box(page,'grandmaster:beyond').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('ArrowUp');assert.equal(await box(page,'grandmaster:legend').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Home');assert.equal(await box(page,'unranked').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('ArrowDown');assert.equal(await box(page,'beginner').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Space');assert.equal(await box(page,'beginner').isChecked(),false);await page.keyboard.press('Enter');assert.equal(await box(page,'beginner').isChecked(),true);await page.keyboard.press('Tab');assert.equal(await page.getByRole('dialog').evaluate(e=>e.contains(document.activeElement)),true);await page.keyboard.press('Shift+Tab');await page.keyboard.press('Escape');assert.equal(await trigger(page).evaluate(e=>e===document.activeElement),true);
await open(page);await draft(page,custom);delay=1000;const n=count(name);
await page.getByRole('dialog').getByRole('button',{name:'適用',exact:true}).click();await wait(100);
assert.equal(await page.getByRole('status').filter({hasText:/読み込み中|ランク条件を適用中/}).isVisible(),true);
assert.equal(await trigger(page).evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Tab');
const snapshot=()=>({tag:document.activeElement.tagName,name:document.activeElement.getAttribute('name'),text:document.activeElement.textContent?.slice(0,80),href:document.activeElement.getAttribute('href')});
const target=await page.evaluate(snapshot);if(route==='environment')assert.equal(target.text,'自分の分析を見る');else assert.equal(target.name,'environment');
await settled(page);delay=0;assert.equal(count(name)-n,1);assert.deepEqual(await page.evaluate(snapshot),target);report.focus.push({route,width,next:target});
await trigger(page).focus();await page.keyboard.press('Shift+Tab');assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('name')),route==='environment'?'period':'winRateMode');report.checks.push(route+' keyboard, focus pending/settled '+width);}
for(const width of [320,390,430]){await page.setViewportSize({width,height:844});await open(page);const d=page.getByRole('dialog'),bounds=await d.boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=width+1&&bounds.y>=0&&bounds.y+bounds.height<=844);await box(page,'grandmaster:beyond').scrollIntoViewIfNeeded();assert.ok(await d.getByRole('button',{name:'適用',exact:true}).isVisible());assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:out+'/'+route+'-rank-'+width+'.png'});await page.keyboard.press('Escape');report.mobile.push({route,width,bounds});}
const touch=await context(sessions[0],{viewport:{width:390,height:844},isMobile:true,hasTouch:true});const tp=await touch.newPage();await tp.goto(origin+'/'+route+'?environment='+f.env.rankThree,{waitUntil:'networkidle'});await trigger(tp).tap();await tp.getByRole('dialog').getByRole('button',{name:'GrandMaster',exact:true}).tap();await box(tp,'grandmaster:beyond').scrollIntoViewIfNeeded();await box(tp,'grandmaster:beyond').tap();await tp.getByRole('dialog').getByRole('button',{name:'適用',exact:true}).tap();await settled(tp);assert.equal(new URL(tp.url()).searchParams.get('ranks'),atoms.slice(12,16).join(','));await touch.close();report.checks.push(route+' mobile/touch');
}
await require('./analysis-reset.browser.cjs').checkAnalysisReset({page,origin,environment:f.env.rankThree,atoms,custom,open,draft,apply,settled,count,report,out});
// Existing header prefetch may enrich home's bounded recent records with rank labels. No aggregate fallback is allowed.
for(const read of report.matchReads||[])assert.deepEqual(read,{columns:'id,rank_tier,master_group,grandmaster_rating',limit:'50',bounded:true,ownUser:true});assert.ok((report.matchReads||[]).length<=count('get_home_dashboard'));report.checks.push('no raw-match aggregation fallback; only bounded existing home rank enrichment');
// Exact handoff into actual analysis, followed by real PNG export.
await page.setViewportSize({width:1365,height:1000});await page.goto(origin+'/environment?environment='+f.env.rankThree+'&ranks='+encodeURIComponent(custom.join(',')),{waitUntil:'networkidle'});await page.getByRole('link',{name:'自分の分析を見る'}).click();await settled(page);assert.equal(await page.locator('input[name=ranks]').inputValue(),custom.join(','));const download=page.waitForEvent('download');if(await page.getByRole('button',{name:'デッキ別サマリー（反転込み）をPNG保存',exact:true}).count()){await page.getByRole('button',{name:'デッキ別サマリー（反転込み）をPNG保存',exact:true}).click();}else{await page.getByRole('button',{name:'使用デッキ別サマリーをPNG保存',exact:true}).click();}const file=await download;await file.saveAs(out+'/analysis-export.png');assert.ok(fs.statSync(out+'/analysis-export.png').size>1000);report.checks.push('environment to actual analysis preserves all selected atoms; PNG download');
for(const [env,status]of [[f.env.empty,'データなし'],[f.env.one,'データ量が少ないため非表示'],[f.env.rankThree,'登録戦績']]){await page.goto(origin+'/environment?environment='+env+'&period=24h',{waitUntil:'networkidle'});assert.match(await page.locator('main').innerText(),new RegExp(status));for(const heading of ['遭遇率TOP5','勝率TOP5','増加TOP3','減少TOP3','デッキ別データ'])assert.ok(await page.getByRole('heading',{name:heading,exact:true}).count());const data=page.locator('section').filter({has:page.getByRole('heading',{name:'デッキ別データ',exact:true})});assert.ok(!(await data.innerText()).includes('Shared inactive'));assert.ok(!(await data.innerText()).includes('未分類'));}report.checks.push('E1 panels/privacy/empty/active-only rows');
// An invalid selection fails closed, never broadens to all.
for(const route of ['environment','analysis']){const name=route==='environment'?'get_environment_dashboard_aggregates_v2':'get_analysis_aggregates_v3',n=count(name);await page.goto(origin+'/'+route+'?environment='+f.env.rankThree+'&ranks=master-plus',{waitUntil:'networkidle'});assert.ok(await page.getByRole('alert').count());assert.equal(count(name),n);}report.checks.push('invalid page URL issues no aggregate RPC');
const admin=await context(sessions[4]),ap=await admin.newPage();ap.on('pageerror',e=>report.errors.push(e.message));for(const route of ['/','/matches','/analysis','/matrix','/admin/weekly-report','/admin','/guest']){const response=await ap.goto(origin+route,{waitUntil:'networkidle'});assert.equal(response.status(),200,route);assert.equal(new URL(ap.url()).pathname,route);assert.ok(await ap.locator('h1').count());}await ap.goto(origin+'/analysis?scope=all&environment='+f.env.rankThree+'&ranks='+encodeURIComponent(custom.join(',')),{waitUntil:'networkidle'});assert.equal(report.calls.filter(c=>c.name==='get_analysis_aggregates_v3').at(-1).args.p_include_all_users,true);await admin.close();report.checks.push('existing seven routes and analysis admin scope');
assert.deepEqual(report.errors,[]);report.passed=true;console.log(JSON.stringify({passed:true,checks:report.checks,focus:report.focus,counts:report.calls.reduce((a,c)=>(a[c.name]=(a[c.name]||0)+1,a),{})}));
}catch(e){report.failure=e.stack;if(debugPage){report.failureUrl=debugPage.url();report.failureText=await debugPage.locator("body").innerText().catch(()=>"");await debugPage.screenshot({path:out+"/failure.png"}).catch(()=>{});}throw e;}finally{fs.writeFileSync(out+'/browser.json',JSON.stringify(report,null,2));if(browser)await browser.close();if(app)app.kill();if(proxy)await new Promise(r=>proxy.close(r));}})().catch(e=>{console.error(e.stack);process.exitCode=1;});
